"""
Step 7: Deploy.

Shows a review summary, asks for confirmation, then:
1. Generates ansible/inventory/hosts.yml
2. Generates ansible/group_vars/vault.yml (ansible-vault encrypted)
3. Runs ansible-playbook with subprocess, streaming output
4. On success: prints a celebration banner
"""
from __future__ import annotations

import os
import subprocess
import tempfile
from pathlib import Path

import questionary
from rich.console import Console
from rich.panel import Panel
from rich.rule import Rule
from rich.table import Table
from rich.text import Text
from rich import print as rprint

from wizard import state as wstate
from wizard.diagrams.ascii import deployment_flow

console = Console()

STEP_NAME = "deploy"
TOTAL_STEPS = 6

# Repo root (relative to wizard package location)
_WIZARD_DIR = Path(__file__).parent.parent
_REPO_ROOT = _WIZARD_DIR.parent


def _header() -> None:
    console.print(Panel(
        "[bold]Almost there![/bold] Let's review everything before we deploy.\n\n"
        "When you confirm, the wizard will:\n"
        "  1. Write Ansible configuration files\n"
        "  2. Encrypt your secrets with ansible-vault\n"
        "  3. Connect to your server and install everything automatically\n\n"
        "What gets installed:\n"
        "  • [cyan]Bluesky PDS[/cyan] — your personal Bluesky server (public via Cloudflare)\n"
        "  • [cyan]Portainer CE[/cyan] — a visual dashboard for managing your server\n"
        "    [dim](accessible only from your private Tailscale network — not exposed publicly)[/dim]\n"
        "  • [cyan]MinIO[/cyan] — blob storage for your media\n"
        "  • [cyan]Cloudflare tunnel[/cyan] + [cyan]Tailscale mesh[/cyan]\n\n"
        "[dim]This takes about 5–10 minutes. Don't close the terminal![/dim]",
        title="[bold blue]Step {} of {}  —  Review & Deploy[/bold blue]".format(TOTAL_STEPS, TOTAL_STEPS),
        border_style="blue",
        padding=(1, 2),
    ))
    console.print()


def _show_review(state: dict) -> None:
    console.print(Rule("[bold]Configuration Summary[/bold]"))
    console.print()

    table = Table(show_header=False, box=None, padding=(0, 2))
    table.add_column("Field", style="bold cyan", no_wrap=True)
    table.add_column("Value", style="white")

    table.add_row("Deployment Profile", state.get("deployment_profile", "cloud"))
    table.add_row("Server IP", state.get("server_ip", "[red]NOT SET[/red]"))
    table.add_row("Domain", state.get("domain", "[red]NOT SET[/red]"))
    table.add_row("Cloudflare Token", "[green]✓ configured[/green]" if state.get("cloudflare_token") else "[red]NOT SET[/red]")
    table.add_row("Tailscale Auth Key", "[green]✓ configured[/green]" if state.get("tailscale_auth_key") else "[red]NOT SET[/red]")
    table.add_row("Admin Password", "[green]✓ configured[/green]" if state.get("admin_password") else "[red]NOT SET[/red]")
    table.add_row("JWT Secret", "[green]✓ generated[/green]" if state.get("jwt_secret") else "[red]NOT GENERATED[/red]")
    table.add_row("PLC Rotation Key", "[green]✓ generated[/green]" if state.get("plc_rotation_key") else "[red]NOT GENERATED[/red]")

    console.print(table)
    console.print()


def _check_required(state: dict) -> list[str]:
    """Return list of missing required fields."""
    required = {
        "server_ip": "VPS IP address",
        "server_password": "Server root password",
        "domain": "Domain name",
        "cloudflare_token": "Cloudflare tunnel token",
        "tailscale_auth_key": "Tailscale auth key",
        "admin_password": "Admin password",
        "jwt_secret": "JWT secret (generated)",
        "plc_rotation_key": "PLC rotation key (generated)",
    }
    missing = []
    for key, label in required.items():
        if not state.get(key):
            missing.append(label)
    return missing


def _deploy_portainer(state: dict, repo_root: Path) -> None:
    """Copy portainer compose file to deployment dir and note it in state."""
    portainer_src = repo_root / "compose" / "portainer" / "compose.yml"
    if portainer_src.exists():
        console.print(f"[green]✓ Portainer compose stack ready at {portainer_src}[/green]")
    else:
        console.print(f"[yellow]⚠  Portainer compose file not found at {portainer_src} — skipping[/yellow]")


def _generate_hosts_yml(state: dict, dest: Path) -> None:
    """Write ansible inventory hosts.yml."""
    dest.parent.mkdir(parents=True, exist_ok=True)
    content = f"""# Generated by my-net wizard
# DO NOT EDIT MANUALLY — re-run the wizard to regenerate

all:
  hosts:
    my-net-server:
      ansible_host: {state['server_ip']}
      ansible_user: root
      ansible_ssh_pass: "{{{{ vault_server_ssh_password }}}}"
      ansible_become: yes
  vars:
    mynet_domain: {state['domain']}
    mynet_admin_email: admin@{state['domain']}
"""
    dest.write_text(content)
    console.print(f"[green]✓ Generated {dest}[/green]")


def _generate_vault_yml(state: dict, dest: Path, vault_password: str) -> None:
    """Write and encrypt ansible vault file."""
    dest.parent.mkdir(parents=True, exist_ok=True)

    plaintext = f"""# Encrypted by my-net wizard with ansible-vault
# Decrypt with: ansible-vault decrypt ansible/group_vars/vault.yml

vault_server_ssh_password: "{state['server_password']}"
vault_cloudflare_tunnel_token: "{state['cloudflare_token']}"
vault_tailscale_auth_key: "{state['tailscale_auth_key']}"
vault_admin_password: "{state['admin_password']}"
vault_jwt_secret: "{state['jwt_secret']}"
vault_plc_rotation_key: "{state['plc_rotation_key']}"
"""

    # Write plaintext to temp file, then encrypt in place
    with tempfile.NamedTemporaryFile(mode="w", suffix=".yml", delete=False) as tmp:
        tmp.write(plaintext)
        tmp_path = tmp.name

    with tempfile.NamedTemporaryFile(mode="w", suffix=".pass", delete=False) as pf:
        pf.write(vault_password)
        pass_path = pf.name

    try:
        result = subprocess.run(
            ["ansible-vault", "encrypt", tmp_path, "--vault-password-file", pass_path, "--output", str(dest)],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            # Fallback: write plaintext with warning if ansible-vault fails
            console.print(f"[yellow]⚠ ansible-vault encrypt failed: {result.stderr.strip()}[/yellow]")
            console.print("[yellow]Writing unencrypted vault file — secure your server![/yellow]")
            dest.write_text(plaintext)
        else:
            console.print(f"[green]✓ Generated and encrypted {dest}[/green]")
    finally:
        os.unlink(tmp_path)
        os.unlink(pass_path)


def _stream_ansible(state: dict, repo_root: Path, vault_password: str) -> bool:
    """Run ansible-playbook and stream output. Returns True on success."""
    playbook = repo_root / "ansible" / "playbooks" / "provision-node.yml"
    inventory = repo_root / "ansible" / "inventory" / "hosts.yml"

    if not playbook.exists():
        rprint(f"[red]Playbook not found: {playbook}[/red]")
        rprint("[yellow]Make sure you're running from the my-net repo directory.[/yellow]")
        return False

    with tempfile.NamedTemporaryFile(mode="w", suffix=".pass", delete=False) as pf:
        pf.write(vault_password)
        pass_path = pf.name

    console.print()
    console.print(Rule("[bold cyan]Running Ansible Playbook[/bold cyan]"))
    console.print()

    cmd = [
        "ansible-playbook",
        str(playbook),
        "-i", str(inventory),
        "--vault-password-file", pass_path,
        "--diff",
    ]

    try:
        process = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
        )

        for line in process.stdout:
            line = line.rstrip()
            if line.startswith("TASK"):
                console.print(f"[bold cyan]{line}[/bold cyan]")
            elif "ok:" in line or "changed:" in line:
                console.print(f"[green]{line}[/green]")
            elif "failed:" in line or "FAILED" in line:
                console.print(f"[red]{line}[/red]")
            elif "skipping:" in line:
                console.print(f"[dim]{line}[/dim]")
            elif line.startswith("PLAY RECAP"):
                console.print(f"[bold]{line}[/bold]")
            else:
                console.print(line)

        process.wait()
        return process.returncode == 0

    except FileNotFoundError:
        rprint("[red]ansible-playbook not found — is ansible-core installed?[/red]")
        rprint("[yellow]Try: pip install ansible-core[/yellow]")
        return False
    finally:
        os.unlink(pass_path)


def _celebrate(domain: str, server_ip: str = "") -> None:
    server_url = f"https://{domain}"
    health_url = f"{server_url}/xrpc/_health"
    # Portainer is accessible via Tailscale hostname or IP — not via Cloudflare
    tailscale_hint = server_ip if server_ip else "<tailscale-ip>"
    portainer_url = f"https://{tailscale_hint}:9443"

    console.print()
    console.print(Panel(
        Text.assemble(
            ("🎉  ", "bold"),
            ("YOUR SOVEREIGN CLOUD IS LIVE!", "bold green"),
            ("  🎉", "bold"),
            "\n\n",
            # PDS
            ("── Bluesky PDS (public) ────────────────────────\n", "dim"),
            ("  Server URL:   ", "bold"),
            (server_url, "bold cyan"),
            "\n",
            ("  Health check: ", "bold"),
            (health_url, "cyan"),
            "\n",
            ("  Your handle:  ", "bold"),
            (f"@{domain}", "bold white"),
            "\n\n",
            # Portainer
            ("── Portainer Dashboard (private mesh only) ─────\n", "dim"),
            ("  Portainer:    ", "bold"),
            (portainer_url, "bold cyan"),
            "\n",
            ("  ", ""),
            ("⚠ Accessible only via Tailscale — connect your devices first", "yellow"),
            "\n\n",
            # Next steps
            ("── Next steps ───────────────────────────────────\n", "dim"),
            ("  1. Visit ", ""),
            (server_url, "cyan"),
            (" to create your Bluesky account\n", ""),
            ("  2. Install Tailscale on your laptop/phone:\n", ""),
            ("     ", ""),
            ("https://tailscale.com/download", "cyan"),
            ("\n", ""),
            ("  3. Open Portainer at ", ""),
            (portainer_url, "cyan"),
            (" to manage your server\n", ""),
            ("  4. Set up monitoring in Grafana (see docs/)\n", ""),
        ),
        title="[bold green]✓ Deployment Complete![/bold green]",
        border_style="green",
        padding=(1, 2),
    ))
    console.print()
    console.print("[dim]Built with ❤️  by my-net — your data, your rules.[/dim]")
    console.print()


def run(wizard_state: dict) -> dict:
    """Run the deploy step. Returns updated state."""
    _header()
    _show_review(wizard_state)

    # Check for missing required fields
    missing = _check_required(wizard_state)
    if missing:
        console.print(Panel(
            "[red]Missing required configuration:[/red]\n\n" +
            "\n".join(f"  • {m}" for m in missing) +
            "\n\n[yellow]Please re-run the wizard to fill in the missing fields.[/yellow]",
            border_style="red",
            title="[red]Cannot Deploy[/red]",
        ))
        return wizard_state

    console.print(Panel(
        deployment_flow(),
        title="[bold]What happens next[/bold]",
        border_style="dim",
        padding=(0, 1),
    ))
    console.print()

    confirmed = questionary.confirm(
        "Everything look good? Ready to deploy?",
        default=False,
    ).ask()

    if not confirmed:
        rprint("[yellow]No problem — re-run the wizard any time to deploy.[/yellow]")
        return wizard_state

    console.print()
    console.print(Rule("[bold cyan]Starting Deployment[/bold cyan]"))
    console.print()

    # Use repo root for ansible files
    repo_root = _REPO_ROOT

    with console.status("[bold cyan]Generating Ansible inventory...[/bold cyan]", spinner="dots"):
        _generate_hosts_yml(wizard_state, repo_root / "ansible" / "inventory" / "hosts.yml")

    with console.status("[bold cyan]Encrypting secrets with ansible-vault...[/bold cyan]", spinner="dots"):
        _generate_vault_yml(
            wizard_state,
            repo_root / "ansible" / "group_vars" / "vault.yml",
            vault_password=wizard_state["admin_password"],
        )

    _deploy_portainer(wizard_state, repo_root)

    success = _stream_ansible(wizard_state, repo_root, wizard_state["admin_password"])

    if success:
        wizard_state["deployed"] = True
        wstate.mark_step_complete(wizard_state, STEP_NAME)
        _celebrate(wizard_state["domain"], server_ip=wizard_state.get("server_ip", ""))
    else:
        console.print()
        console.print(Panel(
            "[red]Deployment failed.[/red]\n\n"
            "Don't panic — your configuration is saved. Common fixes:\n\n"
            "  • Check that your VPS is reachable (ping it)\n"
            "  • Make sure the Cloudflare tunnel token is correct\n"
            "  • Check for typos in your domain name\n"
            "  • Look at the Ansible output above for specific errors\n\n"
            "[dim]Re-run the wizard to try again. Your answers are saved![/dim]",
            border_style="red",
            title="[red]Deployment Failed[/red]",
            padding=(1, 2),
        ))

    return wizard_state
